config/routes.rb
Rails.application.routes.draw do
  get 'index/home'
  get 'index/index'
  devise_for :admins
  resources :types
  resources :posts
  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :posttypes,dependent: :destroy
  has_many :types,through: :posttypes
  accepts_nested_attributes_for :posttypes
end

app/models/posttype.rb
class Posttype < ApplicationRecord
  belongs_to :post
  belongs_to :type
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :posttypes
  has_many :posts,through: :posttypes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def home
    @posts = Post.all
    @types=Type.all

  end

  def index
    @posts = Post.all
    @types=Type.all
    respond_to :html, :json
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
    @all_types=Type.all
    @post_type=@post.posttypes.build
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
    @all_types=Type.all
    @post_type=@post.posttypes.build
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    params[:types][:id].each do |type|
      if !type.empty?
        @post.posttypes.build(:type_id => type)
      end
    end
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :image_url, :description, :content, :author)
    end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_type, only: [:show, :edit, :update, :destroy]

  # GET /types
  # GET /types.json
  def index
    @types = Type.all
  end

  # GET /types/1
  # GET /types/1.json
  def show
  end

  # GET /types/new
  def new
    @type = Type.new
  end

  # GET /types/1/edit
  def edit
  end

  # POST /types
  # POST /types.json
  def create
    @type = Type.new(type_params)

    respond_to do |format|
      if @type.save
        format.html { redirect_to @type, notice: 'Type was successfully created.' }
        format.json { render :show, status: :created, location: @type }
      else
        format.html { render :new }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /types/1
  # PATCH/PUT /types/1.json
  def update
    respond_to do |format|
      if @type.update(type_params)
        format.html { redirect_to @type, notice: 'Type was successfully updated.' }
        format.json { render :show, status: :ok, location: @type }
      else
        format.html { render :edit }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /types/1
  # DELETE /types/1.json
  def destroy
    @type.destroy
    respond_to do |format|
      format.html { redirect_to types_url, notice: 'Type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type
      @type = Type.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def type_params
      params.require(:type).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/index/Index.html.haml
%h1 abc

app/views/index/home.html.haml
%h1 Index#home
%p Find me in app/views/index/home.html.haml

app/views/index/index.html.haml
#product_list
  %h1 Post
  %table
    - @posts.each do |post|
      %tr{:class => "#{cycle('list_line_odd', 'list_line_even')}"}
        %td
          = image_tag(post.image_url, :class => 'list_image')
        %td.list_description
          %dl
            %dt= post.title
            %dd= truncate(strip_tags(post.description), |
                :length => 80)                            |
        %td.list_actions
          = link_to 'Show', post
          %br/
          = link_to 'Edit', edit_post_path(post)
          %br/
          = link_to 'Destroy', post,         |
            data: { confirm: 'Are you sure?' }, |
            :method => :delete                  |
%br/

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title News
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %p.notice= notice
    %p.alert= alert
    = yield

app/views/posts/_form.html.haml
= form_for @post do |f|
  - if @post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - @post.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :image_url
    = f.text_field :image_url
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :content
    = f.text_area :content
  =fields_for @post_type do |pt|
    .field
      = collection_select(:types, :id, @all_types, :id, :name, {}, {:multiple => true})
  .field
    = f.label :author
    = f.text_field :author
  .actions
    = f.submit 'Save'

app/views/posts/edit.html.haml
%h1 Editing post

= render 'form'

= link_to 'Show', @post
\|
= link_to 'Back', posts_path

app/views/posts/index.html.haml
%h1 Listing posts

%table.table.is-striped
  %thead
    %tr
      %th Title
      %th Image url
      %th Description
      / %th Content
      %th Author
      %th Categories
      %th
      %th
      %th

  %tbody
    - @posts.each do |post|
      %tr
        %td= post.title
        %td= post.image_url
        %td= post.description
        / %td= post.content
        %td= post.author
        %td
          %table.table.is-bordered
            -post.types.each do |type|
              %td=type.name
                
        %td= link_to 'Show', post
        %td= link_to 'Edit', edit_post_path(post)
        %td= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }

%br
= link_to 'Sign out', destroy_admin_session_path, :method => :delete
= link_to 'New Post', new_post_path

app/views/posts/new.html.haml
%h1 New post

= render 'form'

= link_to 'Back', posts_path

app/views/posts/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @post.title
%p
  %b Image url:
  = @post.image_url
%p
  %b Description:
  = @post.description
%p
  %b Content:
  = @post.content
%p
  %b Author:
  = @post.author
%p
  %b Categories:
  -@post.types.each do |t|
    =t.name

= link_to 'Edit', edit_post_path(@post)
\|
= link_to 'Back', posts_path

app/views/types/_form.html.haml
= form_for @type do |f|
  - if @type.errors.any?
    #error_explanation
      %h2= "#{pluralize(@type.errors.count, "error")} prohibited this type from being saved:"
      %ul
        - @type.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .actions
    = f.submit 'Save'

app/views/types/edit.html.haml
%h1 Editing type

= render 'form'

= link_to 'Show', @type
\|
= link_to 'Back', types_path

app/views/types/index.html.haml
%h1 Listing types

%table
  %thead
    %tr
      %th Name
      %th Description
      %th
      %th
      %th

  %tbody
    - @types.each do |type|
      %tr
        %td= type.name
        %td= type.description
        %td= link_to 'Show', type
        %td= link_to 'Edit', edit_type_path(type)
        %td= link_to 'Destroy', type, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Type', new_type_path

app/views/types/new.html.haml
%h1 New type

= render 'form'

= link_to 'Back', types_path

app/views/types/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @type.name
%p
  %b Description:
  = @type.description

= link_to 'Edit', edit_type_path(@type)
\|
= link_to 'Back', types_path